version: "3"
services:
  node-app:
    container_name: express-node-app-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3007:7000"
    # environment:
      # - PORT=8000
      # - NODE_ENV=production
    env_file:
      - ./.env