version: "3"
services:
  node-app:
    build:
      context: .
      # args:
      #   - NODE_END=development
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      # - PORT=8000
      - NODE_ENV=development